name: elie_web
description: elie web app

publish_to: 'none'

version: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.2.0
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.1.1
  syncfusion_flutter_datepicker: ^20.1.59
  get_it: ^7.2.0
  mongo_dart: ^0.7.4+1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  pin_code_fields: ^7.4.0
  top_snackbar_flutter: ^1.1.1
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  flutter_rating_bar: ^4.0.1
  rounded_loading_button: ^2.1.0
  auto_route: ^4.0.1
  google_fonts: ^2.3.2
  fl_chart: ^0.50.6
  data_table_2: ^2.2.2
  audioplayers: ^0.20.1
  flutter_svg: ^1.0.3
  razorpay_flutter: ^1.1.1
  # comment this when building apk for android
  razorpay_web: ^1.3.2
  dotted_border: ^2.0.0+2
  flutter_snake_navigationbar: ^0.6.1
  url_launcher: ^6.1.4
  package_info_plus: ^1.4.2
  json_annotation: ^4.6.0
  cached_network_image: ^3.2.1  

dev_dependencies:
  auto_route_generator: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  json_serializable: ^6.3.1
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.jpg"

flutter_app_name:
  name: "Elie World"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/carousel/
    - images/

  fonts:
    - family: QT
      fonts:
        - asset: fonts/quente-script-pen.ttf
    - family: FT
      fonts:
        - asset: fonts/FutuBk.ttf

    - family: NTS
      fonts:
        - asset: fonts/SFNSDisplay-Ultralight.otf

    - family: HD
      fonts:
        - asset: fonts/heading.otf

    - family: IT
      fonts:
        - asset: fonts/quotes.ttf

    - family: p1
      fonts:
        - asset: fonts/p1.ttf

    - family: p2
      fonts:
        - asset: fonts/p2.ttf


    - family: NT
      fonts:
        - asset: fonts/NeutraTextTF-Book.otf

