name: elie_admin
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  side_navigation: ^1.0.2
  dio: ^4.0.6
  get_it: ^7.2.0
  syncfusion_flutter_datepicker: ^20.1.55
  intl: ^0.17.0
  map: ^1.0.1
  cached_network_image: ^3.2.0
  latlng: ^0.1.0
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.3
  fl_chart: ^0.50.1
  provider: ^6.0.2
  data_table_2: ^2.2.1
  shared_preferences: ^2.0.15
  file_picker: ^4.5.1
  google_geocoding: ^0.2.0
  flutter_datetime_picker: ^1.5.1
  date_picker_timeline: ^1.2.3
  time_range: ^1.0.2
  percent_indicator: ^4.2.2
  top_snackbar_flutter: ^1.0.3
  visibility_aware_state: ^1.0.3
  multi_select_flutter: ^4.1.2
  syncfusion_flutter_calendar: ^20.1.55
  modal_bottom_sheet: ^2.0.1
  flutter_easyloading: ^3.0.5









dev_dependencies:
  build_runner:


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/


  fonts:
    - family: df
      fonts:
        - asset: fonts/Dashboard-Regular.ttf
    - family: inter
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf
