List<String> quotesList = [
  'I am Blessed',
  'I am Resilient',
  'I am Inspired',
  'I am Beautiful',
  'I am Grateful',
  'I am Loved',
  'I am Happy',
  'I am Worthy',
  'I am Thoughtful',
  'I am Compassionate',
  'I am Considerate',
  'I am Gracious',
  'I am Kind',
  'I am Responsible',
  'I am Harmonious',
  'I am Uplifted',
];
