name: elie_expert
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  location: ^4.4.0
  salomon_bottom_bar: ^3.3.1
  dio: ^4.0.6
  get_it: ^7.2.0
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.1.59
  rounded_loading_button: ^2.1.0
  modal_bottom_sheet: ^2.0.1
  syncfusion_flutter_calendar: ^20.1.59
  time_range: ^1.0.2
  date_picker_timeline: ^1.2.3
  map: ^1.0.1
  cached_network_image: ^3.2.1
  latlng: ^0.1.0
  maps_launcher: ^2.0.1
  shared_preferences: ^2.0.15
  top_snackbar_flutter: ^1.1.1
  rating_dialog: ^2.0.4
  multi_select_flutter: ^4.1.2
  file_picker: ^4.6.1
  pin_code_fields: ^7.4.0
  url_launcher: ^6.1.4
  flutter_sms: ^2.3.3
  geocoding: ^2.0.4
  permission_handler: ^10.0.0



dev_dependencies:
  auto_route_generator: ^3.2.3
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.jpg"
flutter_app_name:
  name: "Elie Experts"



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
