List expertiseList = [
  'Cut & style',
  'Styling',
  'Touch up',
  'GLOBAL HAIR COLOR',
  'HIGHLIGHTS',
  'CYSTINE /KERATINE TREARMENT',
  'Botox Hair Treatment',
  'Hair SPA',
  'THREADING',
  'FLAVOURDED WAXING',
  'STRIPLESS WAX',
  'BLEACH/DE-TAN',
  'HAND &FEET',
  'NAILS',
  'MAKEUP',
  'MASSAGES',
  'Body massages',
  'Facial',
  'Organic treatments',
  'Clinical Treatments',
];
